// 50 real Nigerian foodstuffs that are genuinely exported abroad.
//
// Every entry is a commodity Nigeria ships in volume, drawn from NBS and NEPC
// export records: cocoa beans, cocoa butter, cocoa liquor, cocoa powder, shelled
// and in-shell cashew, sesame, soya, shea nuts and shea butter, hibiscus flower,
// ginger, palm oil and palm kernels, yam, cassava products, plantain, frozen
// shrimps and prawns, stockfish, and the grain and legume complex.
//
// Images are hotlinked from Wikimedia Commons via Special:FilePath at 900px.
// Every file was chosen because its curated Commons categories name the actual
// product shown, and most are Nigerian market or processing photos. Attribution
// and licence for each image live on its Commons file description page.

export const products = [
  {
    id: 'cocoa-beans',
    name: 'Cocoa Beans (Standard & Superior Grade)',
    category: 'Pantry',
    price: 78,
    unit: '50 kg jute sack',
    description: 'Fully fermented, sun-dried beans from the Ondo and Cross River belt, graded from standard to Grade I for world grinders.',
    badge: 'Best seller',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cocoa%20seeds%20being%20dried.jpg?width=900',
    tint: 'linear-gradient(135deg, #7c4b31 0%, #331a0e 100%)',
  },
  {
    id: 'cocoa-butter-natural',
    name: 'Natural Cocoa Butter',
    category: 'Pantry',
    price: 88,
    unit: '25 kg block',
    description: 'Pressing-grade cocoa butter — one of Nigeria’s fastest-growing value-added cocoa exports.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cocoa%20butter%20p1410148.JPG?width=900',
    tint: 'linear-gradient(135deg, #f2e1b0 0%, #c9a25a 100%)',
  },
  {
    id: 'cocoa-powder',
    name: 'Cocoa Powder',
    category: 'Pantry',
    price: 74,
    unit: '5 kg bag',
    description: 'Fine, alkalised cocoa powder milled for bakery, coatings, and drink-mix production.',
    badge: 'Popular',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cocoa%20powder.jpg?width=900',
    tint: 'linear-gradient(135deg, #e0cbab 0%, #7a5228 100%)',
  },
  {
    id: 'cocoa-liquor',
    name: 'Cocoa Liquor (Non-Defatted)',
    category: 'Pantry',
    price: 82,
    unit: '25 kg tin',
    description: 'Centrally crushed nibs for chocolate and beverage makers who need unpowdered cocoa mass.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fine%20cocoa%20liquor.jpg?width=900',
    tint: 'linear-gradient(135deg, #b08968 0%, #582f0e 100%)',
  },
  {
    id: 'cashew-nuts-raw',
    name: 'Raw Cashew Nuts',
    category: 'Pantry',
    price: 68,
    unit: '25 kg jute bag',
    description: 'Whole, unprocessed nuts bought direct from Cross River and Benue farm-gate cooperatives.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Noix%20de%20Cajou%20CL%20J%20WEBER%20(23649210776).jpg?width=900',
    tint: 'linear-gradient(135deg, #dfbc83 0%, #7c541f 100%)',
  },
  {
    id: 'cashew-kernels-w320',
    name: 'Roasted Cashew Kernels (W320)',
    category: 'Pantry',
    price: 92,
    unit: '5 kg tin',
    description: 'Steam-blanched golden-grade kernels with no splits or scorched pieces, ready for packing.',
    badge: 'Premium',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cashews2.JPG?width=900',
    tint: 'linear-gradient(135deg, #f4d08a 0%, #b5843a 100%)',
  },
  {
    id: 'sesame-seeds-beniseed',
    name: 'Sesame Seeds (Beniseed)',
    category: 'Pantry',
    price: 62,
    unit: '25 kg bag',
    description: 'High-oil, sortex-clean sesame from Kebbi and Sokoto, in demand from Japan and China.',
    badge: 'Best seller',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nigerian%20Sesame%20seeds%20the%20superfood%20rich%20in%20livegiving%20nutrients.jpg?width=900',
    tint: 'linear-gradient(135deg, #e2cb99 0%, #9e7b44 100%)',
  },
  {
    id: 'palm-oil-red',
    name: 'Refined Red Palm Oil',
    category: 'Pantry',
    price: 34,
    unit: '25 L keg',
    description: 'Vitamin-A rich red palm oil from the South-East and Niger Delta, refined for shipping.',
    badge: 'Everyday value',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Epo%20(red%20palm%20oil).jpg?width=900',
    tint: 'linear-gradient(135deg, #f08b54 0%, #b33612 100%)',
  },
  {
    id: 'palm-kernels',
    name: 'Palm Kernels',
    category: 'Pantry',
    price: 36,
    unit: '25 kg bag',
    description: 'Clean, cracked kernels destined for palm kernel oil mills in Asia and Europe.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sorted%20Palm%20Kernels%20LM.jpg?width=900',
    tint: 'linear-gradient(135deg, #d79b70 0%, #8c5830 100%)',
  },
  {
    id: 'shea-butter-raw',
    name: 'Unrefined Shea Butter (Karite)',
    category: 'Pantry',
    price: 71,
    unit: '25 kg carton',
    description: 'Hand-sorted, unrefined shea butter from northern cooperatives for cosmetics and food use.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shea%20butter.jpg?width=900',
    tint: 'linear-gradient(135deg, #fefae0 0%, #dda15e 100%)',
  },
  {
    id: 'shea-nuts',
    name: 'Shea Nuts (Karite Kernels)',
    category: 'Pantry',
    price: 48,
    unit: '25 kg bag',
    description: 'Whole, unshelled shea kernels collected from Vitellaria parkland across the savanna belt.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kariten%C3%BCsse220109.JPG?width=900',
    tint: 'linear-gradient(135deg, #e8c991 0%, #916c31 100%)',
  },
  {
    id: 'kola-nut',
    name: 'Kola Nuts',
    category: 'Pantry',
    price: 54,
    unit: '25 kg bag',
    description: 'Fresh, bright kola from the South-West and Middle Belt, packed for the export trade.',
    badge: 'Traditional',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kola%20nut%20(oji).jpg?width=900',
    tint: 'linear-gradient(135deg, #faedcd 0%, #d4a373 100%)',
  },
  {
    id: 'bitter-kola',
    name: 'Bitter Kola (Garcinia)',
    category: 'Pantry',
    price: 58,
    unit: '20 kg carton',
    description: 'Aromatic Garcinia kola nuts with a long shelf life, traded as a ritual and herbal good.',
    badge: 'Popular',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bitter%20kolala%20from%20Limbe%20botanic%20garden.jpg?width=900',
    tint: 'linear-gradient(135deg, #817970 0%, #2c2925 100%)',
  },
  {
    id: 'tiger-nuts-aya',
    name: 'Tiger Nuts (Aya)',
    category: 'Pantry',
    price: 44,
    unit: '25 kg bag',
    description: 'Sifted, grade-A tiger nuts from the northern savanna for beverage and snack processing.',
    badge: 'Best seller',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Golden%20Tiger%20Nuts.jpg?width=900',
    tint: 'linear-gradient(135deg, #d7af70 0%, #855c2d 100%)',
  },
  {
    id: 'baobab-pulp',
    name: 'Baobab Fruit Pulp',
    category: 'Pantry',
    price: 46,
    unit: '20 kg bag',
    description: 'De-seeded natural baobab pulp with a tart, high-fibre profile for health-food manufacturing.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Baobab%20fruit%20-%20dry%20pulp%20in%20wooden%20bowl%2C%20Adansonia%20digitata.jpg?width=900',
    tint: 'linear-gradient(135deg, #efe1c0 0%, #a98a52 100%)',
  },
  {
    id: 'moringa-pods',
    name: 'Moringa Seed Pods',
    category: 'Pantry',
    price: 39,
    unit: '20 kg crate',
    description: 'Fresh drumstick pods for herbal tea and oil extraction, packed the same day they are picked.',
    badge: 'New',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Moringa%20Tree%20Branch%20with%20Hanging%20Seed%20Pods.jpg?width=900',
    tint: 'linear-gradient(135deg, #a9d47b 0%, #527a3a 100%)',
  },
  {
    id: 'yam-tubers',
    name: 'White Yam Tubers',
    category: 'Fresh produce',
    price: 32,
    unit: '20 kg crate',
    description: 'Firm, well-cured water yams from the middle belt — the world’s largest producing region.',
    badge: 'Best seller',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Yam%20Tubers%20stacked%20on%20a%20plastic%20table%2001.jpg?width=900',
    tint: 'linear-gradient(135deg, #eac08d 0%, #9b5e3e 100%)',
  },
  {
    id: 'yam-flour-elubo',
    name: 'Yam Flour (Elubo)',
    category: 'Pantry',
    price: 30,
    unit: '25 kg bag',
    description: 'Sun-dried, milled yam slices that cook up into smooth, aromatic amala.',
    badge: 'Popular',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dry%20grinded%20yam%20at%20monday%20market%2001.jpg?width=900',
    tint: 'linear-gradient(135deg, #ffedd8 0%, #d9975f 100%)',
  },
  {
    id: 'cassava-roots',
    name: 'Cassava Roots',
    category: 'Fresh produce',
    price: 22,
    unit: '25 kg bag',
    description: 'Clean, unprocessed cassava from the middle belt — the world’s largest cassava producer.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cassava%20at%20monday%20market%20kaduna%20state%20Nigeria%2001.jpg?width=900',
    tint: 'linear-gradient(135deg, #c49a7a 0%, #613b24 100%)',
  },
  {
    id: 'garri-white',
    name: 'White Garri (Cassava Flakes)',
    category: 'Pantry',
    price: 25,
    unit: '25 kg bag',
    description: 'Granulated, fermented cassava granules from Nigeria’s busiest garri belts in Ogun and Kwara.',
    badge: 'Everyday value',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Garri%20also%20called%20cassava%20flakes.jpg?width=900',
    tint: 'linear-gradient(135deg, #f2ebd9 0%, #b39a6f 100%)',
  },
  {
    id: 'fufu-flour',
    name: 'Cassava Fufu Flour',
    category: 'Pantry',
    price: 27,
    unit: '25 kg bag',
    description: 'Smooth, sift-free fermented cassava flour that sets into a stretchy traditional swallow.',
    badge: 'Popular',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Uyoto%20Iwa%20(Fufu%20production).jpg?width=900',
    tint: 'linear-gradient(135deg, #f5f0eb 0%, #a39688 100%)',
  },
  {
    id: 'plantain-green',
    name: 'Green Plantain Bunches',
    category: 'Fresh produce',
    price: 24,
    unit: '18 kg crate',
    description: 'Mature green plantains that hold their shape through long export transit.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bunch%20of%20Plantain.jpg?width=900',
    tint: 'linear-gradient(135deg, #b5c496 0%, #476127 100%)',
  },
  {
    id: 'dried-okra',
    name: 'Dried Okra (Okoro)',
    category: 'Pantry',
    price: 42,
    unit: '20 kg bag',
    description: 'Sun-dried okra pods sorted for draw, packaged as a ready-made soup thickener.',
    badge: 'Everyday value',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dried%20Okra%20at%20Bakin%20Dogo%20Market%2C%20Kaduna%20North.jpg?width=900',
    tint: 'linear-gradient(135deg, #8fb36c 0%, #3f5e27 100%)',
  },
  {
    id: 'ginger-split-dried',
    name: 'Split Dried Ginger',
    category: 'Pantry',
    price: 52,
    unit: '25 kg bag',
    description: 'High-pungency Nigerian split ginger — the country ranks second in the world for this crop.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dry%20Ginger%201.jpg?width=900',
    tint: 'linear-gradient(135deg, #f4cf70 0%, #c88735 100%)',
  },
  {
    id: 'ginger-powder',
    name: 'Ground Ginger',
    category: 'Pantry',
    price: 41,
    unit: '25 kg bag',
    description: 'Fine, high-volatile-oil ginger powder for seasoning blends and beverage mixes.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ginger%20powder%202.jpg?width=900',
    tint: 'linear-gradient(135deg, #f6d98a 0%, #d99b3d 100%)',
  },
  {
    id: 'garlic-bulbs',
    name: 'Garlic Bulbs',
    category: 'Pantry',
    price: 46,
    unit: '25 kg mesh bag',
    description: 'Firm, cured white garlic from the northern plains, cured for long sea freight.',
    badge: 'Farm fresh',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/-365%20garlic%20harvest%20(28151809812).jpg?width=900',
    tint: 'linear-gradient(135deg, #f0ede6 0%, #9e9587 100%)',
  },
  {
    id: 'turmeric-rhizomes',
    name: 'Turmeric Rhizomes',
    category: 'Pantry',
    price: 38,
    unit: '25 kg bag',
    description: 'Deep-orange, high-curcumin rhizomes dried and cleaned for spice mills.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Curcuma%20longa%20roots.jpg?width=900',
    tint: 'linear-gradient(135deg, #f3e6a8 0%, #c08a1e 100%)',
  },
  {
    id: 'hibiscus-dried',
    name: 'Dried Hibiscus Flowers (Zobo)',
    category: 'Pantry',
    price: 45,
    unit: '20 kg carton',
    description: 'Deep red calyces of Hibiscus sabdariffa, a consistent non-oil export earner.',
    badge: 'Best seller',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hibiscus%20Sabdariffa%20calyxes.jpg?width=900',
    tint: 'linear-gradient(135deg, #d94e4e 0%, #6b1d1d 100%)',
  },
  {
    id: 'dried-chilli',
    name: 'Dried Red Chillies',
    category: 'Pantry',
    price: 44,
    unit: '20 kg bag',
    description: 'Sun-dried, deep-red Capsicum with a clean finish for processors and blenders.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dried%20Red%20Chili.jpg?width=900',
    tint: 'linear-gradient(135deg, #e8543f 0%, #8f1d0b 100%)',
  },
  {
    id: 'cloves',
    name: 'Dried Cloves',
    category: 'Pantry',
    price: 64,
    unit: '20 kg bag',
    description: 'Fragrant, fully dried flower buds for infusion, bakery, and spice blending.',
    badge: 'Premium',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Clove%20sorting.jpg?width=900',
    tint: 'linear-gradient(135deg, #5c3826 0%, #1f120c 100%)',
  },
  {
    id: 'cassia-sticks',
    name: 'Cassia Cinnamon Sticks',
    category: 'Pantry',
    price: 55,
    unit: '20 kg case',
    description: 'Rough, aromatic bark quills rolled whole for tea and food processors.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cassia%20sticks.jpg?width=900',
    tint: 'linear-gradient(135deg, #b08968 0%, #6b4a2f 100%)',
  },
  {
    id: 'uziza-seeds',
    name: 'Uziza Seeds',
    category: 'Pantry',
    price: 50,
    unit: '20 kg bag',
    description: 'Whole Piper guineense seeds with a warm, peppery bite for soups and spice packs.',
    badge: 'Specialty',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Uziza%20Seeds%20at%20Bakin%20Dogo%20Market%2C%20Kaduna%20North.jpg?width=900',
    tint: 'linear-gradient(135deg, #606c38 0%, #283618 100%)',
  },
  {
    id: 'ehuru-seeds',
    name: 'Ehuru (Calabash Nutmeg)',
    category: 'Pantry',
    price: 58,
    unit: '15 kg pack',
    description: 'Whole Monodora myristica seeds, the aromatic backbone of traditional pepper soup.',
    badge: 'Specialty',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Monodora%20myristica%20seeds.png?width=900',
    tint: 'linear-gradient(135deg, #996538 0%, #472913 100%)',
  },
  {
    id: 'alligator-pepper',
    name: 'Alligator Pepper (Atare)',
    category: 'Pantry',
    price: 56,
    unit: '15 kg pack',
    description: 'Dried Aframomum pods and their fiery seeds, packed for the ceremonial and culinary trade.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Grains%20of%20paradise%20(Aframomum%20melegueta).jpg?width=900',
    tint: 'linear-gradient(135deg, #8cb369 0%, #31471b 100%)',
  },
  {
    id: 'locust-beans-iru',
    name: 'Fermented Locust Beans (Iru)',
    category: 'Pantry',
    price: 37,
    unit: '20 kg bag',
    description: 'Fermented Parkia biglobosa seeds with the deep savoury funk that anchors native soups.',
    badge: 'Traditional',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/DADAWAN.jpg?width=900',
    tint: 'linear-gradient(135deg, #9b5e3e 0%, #3b2011 100%)',
  },
  {
    id: 'ogbono-seeds',
    name: 'Ogbono Wild Mango Seeds',
    category: 'Pantry',
    price: 59,
    unit: '20 kg bag',
    description: 'Cleaned Irvingia kernels that thicken and draw soups to a silky finish.',
    badge: 'Premium',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ogbono%20seed.jpg?width=900',
    tint: 'linear-gradient(135deg, #c88735 0%, #633c12 100%)',
  },
  {
    id: 'achi-seeds',
    name: 'Achi Seeds',
    category: 'Pantry',
    price: 47,
    unit: '20 kg bag',
    description: 'Brachystegia eurycoma kernels milled to an aromatic, efficient soup thickener.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Brachystegia%20Eurycoma%20(%20Ach%E1%BB%8B)%20Marchant%20at%20Lagwa%2C%20Abo%20Mbaise%2C%20Imo%20state.jpg?width=900',
    tint: 'linear-gradient(135deg, #d7b593 0%, #73502e 100%)',
  },
  {
    id: 'shrimps-prawns-frozen',
    name: 'Frozen Shrimps & Prawns',
    category: 'Pantry',
    price: 88,
    unit: '10 kg carton',
    description: 'Block-frozen Atlantic catch, quick-frozen at landing for Asian and European buyers.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Frozen%20raw%20shrimps.jpg?width=900',
    tint: 'linear-gradient(135deg, #f49a7a 0%, #b34a36 100%)',
  },
  {
    id: 'catfish-smoked',
    name: 'Smoked Catfish',
    category: 'Pantry',
    price: 46,
    unit: '10 kg carton',
    description: 'Wood-smoked, gutted and oven-dried catfish from River State and Delta landings.',
    badge: 'Popular',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dried%20smoked%20catfish.jpg?width=900',
    tint: 'linear-gradient(135deg, #9e7b44 0%, #3d2c18 100%)',
  },
  {
    id: 'stockfish-dried',
    name: 'Dried Stockfish',
    category: 'Pantry',
    price: 39,
    unit: '25 kg bag',
    description: 'Fermented, sun-cured stockfish graded by size and packed for the export soup trade.',
    badge: 'Everyday value',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Various%20sizes%20of%20stockfish%20head.jpg?width=900',
    tint: 'linear-gradient(135deg, #b8c2cc 0%, #4e5d6c 100%)',
  },
  {
    id: 'giant-african-snail',
    name: 'Giant African Snail Meat',
    category: 'Pantry',
    price: 68,
    unit: '10 kg carton',
    description: 'Cleaned, trimmed giant snail meat from the South-East, vacuum-packed for export.',
    badge: 'Specialty',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pepper%20Snail%20delicacy.jpg?width=900',
    tint: 'linear-gradient(135deg, #d4a373 0%, #453227 100%)',
  },
  {
    id: 'soya-beans',
    name: 'Soya Beans',
    category: 'Pantry',
    price: 35,
    unit: '25 kg bag',
    description: 'Whole, sortex-clean beans for soy meal milling — a regular feature of Nigeria’s agri exports.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Closeup%20of%20High%20Oleic%20Soybeans%20(10873119213).jpg?width=900',
    tint: 'linear-gradient(135deg, #cdbd8a 0%, #71603a 100%)',
  },
  {
    id: 'guinea-corn-sorghum',
    name: 'Guinea Corn (Sorghum)',
    category: 'Pantry',
    price: 27,
    unit: '25 kg bag',
    description: 'Cleaned sorghum grain from Kano and Kaduna, where Nigeria ranks second worldwide.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Guinea%20corn%20seed.jpg?width=900',
    tint: 'linear-gradient(135deg, #c9dc7a 0%, #537532 100%)',
  },
  {
    id: 'cowpeas-brown',
    name: 'Brown Cowpeas',
    category: 'Pantry',
    price: 31,
    unit: '25 kg bag',
    description: 'Pest-managed cowpeas meeting improved export-rejection targets set with ITC partners.',
    badge: 'Export grade',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Black%20cowpea.jpg?width=900',
    tint: 'linear-gradient(135deg, #f2e1b0 0%, #b09153 100%)',
  },
  {
    id: 'bambara-groundnut',
    name: 'Bambara Groundnut',
    category: 'Pantry',
    price: 33,
    unit: '25 kg bag',
    description: 'Drought-tolerant, protein-rich nuts from Kaduna and the North-West.',
    badge: 'New',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bambara%20nuts%20on%20sale%20at%20the%20Monday%20Market%20in%20Kakuri%2C%20Kaduna%2001.jpg?width=900',
    tint: 'linear-gradient(135deg, #c9b28a 0%, #7a6136 100%)',
  },
  {
    id: 'pigeon-peas',
    name: 'Pigeon Peas (Fio-Fio)',
    category: 'Pantry',
    price: 30,
    unit: '25 kg bag',
    description: 'Clean, sorted pigeon peas for porridges and food-aid contracts.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Graines%20du%20poids%20d%27Angole%20au%20B%C3%A9nin1.jpg?width=900',
    tint: 'linear-gradient(135deg, #c4a47c 0%, #614624 100%)',
  },
  {
    id: 'millet-pearl',
    name: 'Pearl Millet',
    category: 'Pantry',
    price: 26,
    unit: '25 kg bag',
    description: 'Whole pearl millet grain for tuwo, porridges, and gluten-free milling.',
    badge: null,
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pennisetumglaucumgrain.jpg?width=900',
    tint: 'linear-gradient(135deg, #d7af70 0%, #855c2d 100%)',
  },
  {
    id: 'groundnuts-in-shell',
    name: 'Groundnuts in Shell',
    category: 'Pantry',
    price: 29,
    unit: '25 kg bag',
    description: 'Whole, unshelled groundnuts for roasting and oil pressing from the northern savanna belt.',
    badge: 'Everyday value',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Groundnuts.jpg?width=900',
    tint: 'linear-gradient(135deg, #d79b70 0%, #7d4825 100%)',
  },
  {
    id: 'dates-dried-dabino',
    name: 'Dried Dates (Dabino)',
    category: 'Pantry',
    price: 43,
    unit: '20 kg box',
    description: 'Sun-dried date fruit from northern markets, packed for sweetening and snack trade.',
    badge: 'Natural',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pile%20of%20Dried%20Dates%20at%20Barkin%20Dogo%20Market%2C%20Kaduna%20North%2002.jpg?width=900',
    tint: 'linear-gradient(135deg, #b07843 0%, #4a2c11 100%)',
  },
  {
    id: 'ukwa-breadfruit',
    name: 'Ukwa (African Breadfruit Seeds)',
    category: 'Pantry',
    price: 52,
    unit: '20 kg bag',
    description: 'Parboiled, shelled African breadfruit seeds for porridge and traditional delicacies.',
    badge: 'Premium',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20basin%20of%20already%20washed%20breadfruit%20seed.jpg?width=900',
    tint: 'linear-gradient(135deg, #c9a06a 0%, #603813 100%)',
  },
];
